name: Deploy Dash App

on:
  push:
    branches:
      - main  # или ваша основная ветка

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.7'  # Укажите нужную версию Python

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Dash app
      run: |
        nohup python app.py &
        node server.js